{% set version = "1.4.7" %}

package:
  name: kiwisolver
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/k/kiwisolver/kiwisolver-{{ version }}.tar.gz
  sha256: 9893ff81bd7107f7b685d3017cc6583daadb4fc26e4a888350df530e41980a60

build:
  number: 0
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler("cxx") }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - cppy >=1.2.0
    - setuptools >=42
    - setuptools-scm >=3.4.3
  run:
    - python
    - typing-extensions  # [py<38]

test:
  imports:
    - kiwisolver
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/nucleic/kiwi
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: A fast implementation of the Cassowary constraint solver

extra:
  recipe-maintainers:
    - blink1073
    - licode
    - MatthieuDartiailh
    - sccolbert
    - tacaswell
    - ocefpaf
