{% set version = "1.0.1" %}
package:
  name: kiwisolver
  version: {{ version }}

source:
  fn: kiwisolver-{{ version }}.tar.gz
  url: https://github.com/nucleic/kiwi/archive/{{ version }}.tar.gz
  sha256: ce3be5d520b4d2c3e5eeb4cd2ef62b9b9ab8ac6b6fedbaa0e39cdb6f50644278

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - kiwisolver

about:
  home: https://github.com/nucleic/kiwi
  license: BSD 3-Clause
  summary: A fast implementation of the Cassowary constraint solver

extra:
  recipe-maintainers:
    - blink1073
    - ericdill
    - licode
    - MatthieuDartiailh
    - sccolbert
    - tacaswell
