{% set version = "1.4.8" %}

package:
  name: kiwisolver
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/k/kiwisolver/kiwisolver-{{ version }}.tar.gz
  sha256: 23d5f023bdc8c7e54eb65f03ca5d5bb25b601eac4d7f1a042888a1f45237987e

build:
  number: 1
  skip: true  # [py<310]
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler("cxx") }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - cppy >=1.3.0
    - setuptools >=61.2
    - setuptools-scm >=3.4.3
  run:
    - python
test:
  imports:
    - kiwisolver
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/nucleic/kiwi
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: A fast implementation of the Cassowary constraint solver

extra:
  recipe-maintainers:
    - blink1073
    - licode
    - MatthieuDartiailh
    - sccolbert
    - tacaswell
    - ocefpaf
    - fhoehle
